#!/usr/bin/env python3
"""
summarize.py — fold run.jsonl into the one JSON the page imports, and keep it honest.

    run.jsonl  ──▶  src/data/run-capture.json  ──▶  /run

    # after a pipeline run, refresh the committed capture
    .venv/bin/python tools/capture/summarize.py ingest-runs/<id>/run.jsonl --write

    # in the gate: does the committed capture still equal a fresh fold of its source?
    .venv/bin/python tools/capture/summarize.py --check

WHY A DERIVED FILE AND NOT A DIRECT READ. The page is a React Server Component on Vercel,
where the pipeline's working directory does not exist — ingest-runs/ is a local artifact
tree on the scorer box. Something has to cross that gap, and the two options are a
database round-trip (which makes a static page dynamic, and means a broken connection
renders as an error where a build-time constant cannot) or a committed file. This is the
committed file. It is imported as a module rather than read with path.join because
AGENTS.md records what the other way costs: report.ts's path.join read pulled all of
public/preflight/ into the serverless function's trace.

WHY --check EXISTS. A derived artifact that is regenerated by hand is a stale artifact
with extra steps; tools/demo/check_coherence.py is in the gate for exactly this reason.
So the fold is deterministic — no clocks, no ordering by dict iteration — and the gate
re-folds run.jsonl and compares. If someone edits src/data/run-capture.json to make the
page say something nicer, the gate fails and names the field. That is the property worth
having: **the page cannot say anything the run did not.**

The fold is deliberately lossless-ish rather than clever. It groups events under their
stage, keeps every log line, and computes nothing except elapsed time and counts. There
is no place here to launder a number.
"""

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from tools.capture.recorder import STAGE_KEYS                            # noqa: E402

# Where the committed capture lives, and the pointer back to the run that produced it.
CAPTURE = ROOT / "src" / "data" / "run-capture.json"
SOURCE_KEY = "sourceJsonl"

# --write COPIES the run.jsonl in here rather than pointing at where it was produced.
# ingest-runs/ is gitignored (it holds the videos, which are large and not ours to
# redistribute), so a capture that pointed there would re-derive on the operator's laptop
# and nowhere else — the gate would pass locally and fail, or worse silently skip, on a
# fresh checkout. Copying the one small text file is what makes `--check` mean something
# to anyone other than the person who ran the pipeline.
CAPTURES = ROOT / "captures"

# A log tail rather than the whole thing: process_batch.py is chatty per-frame and a
# committed page does not need forty thousand lines to be credible. The cut is recorded
# (`logTruncated`) so the page can say it happened rather than implying the tool was quiet.
MAX_LOG_LINES = 40


def fold(events, source=None):
    """run.jsonl events -> the page's shape. Pure; same input, same bytes out."""
    begin = next((e for e in events if e["kind"] == "run.begin"), None)
    end = next((e for e in events if e["kind"] == "run.end"), None)
    env = next((e for e in events if e["kind"] == "env"), None)
    if begin is None:
        raise SystemExit("no run.begin event — this is not a capture")

    stages, order = {}, []
    for e in events:
        kind, key = e["kind"], e.get("stage")
        if kind == "stage.begin":
            stages[key] = {
                "key": key, "title": e.get("title") or key, "status": "failed",
                "reason": "the run ended before this stage did",
                "startMs": e["tMs"], "elapsedMs": None,
                "facts": [], "artifacts": [], "log": [], "logTruncated": 0,
            }
            order.append(key)
        elif kind == "fact" and key in stages:
            for k, v in (e.get("values") or {}).items():
                stages[key]["facts"].append({"k": k, "v": v})
        elif kind == "artifact" and key in stages:
            stages[key]["artifacts"].append({
                m: e.get(m) for m in ("path", "role", "label", "present", "bytes", "sha256")
            })
        elif kind == "log" and key in stages:
            stages[key]["log"].append({"stream": e.get("stream", "stdout"), "text": e.get("text", "")})
        elif kind == "stage.end" and key in stages:
            stages[key].update(status=e.get("status", "ok"), reason=e.get("reason"),
                               elapsedMs=e.get("elapsedMs"))

    for s in stages.values():
        if len(s["log"]) > MAX_LOG_LINES:
            s["logTruncated"] = len(s["log"]) - MAX_LOG_LINES
            s["log"] = s["log"][-MAX_LOG_LINES:]

    unknown = [k for k in order if k not in STAGE_KEYS]
    if unknown:
        raise SystemExit(f"stage key(s) the page cannot title: {unknown}. "
                         "Add them to STAGE_KEYS and to src/lib/run-capture.ts.")

    ran = [stages[k] for k in order]
    out = {
        "runId": begin.get("runId"),
        "startedAt": begin.get("startedAt"),
        "argv": begin.get("argv", []),
        "status": (end or {}).get("status", "incomplete"),
        "elapsedMs": (end or {}).get("elapsedMs"),
        "env": {k: v for k, v in (env or {}).items() if k not in ("seq", "tMs", "kind")},
        "stages": ran,
        "counts": {
            "ok": sum(1 for s in ran if s["status"] == "ok"),
            "skipped": sum(1 for s in ran if s["status"] == "skipped"),
            "failed": sum(1 for s in ran if s["status"] == "failed"),
        },
        "outputs": {k: v for k, v in (end or {}).items()
                    if k not in ("seq", "tMs", "kind", "status", "elapsedMs", "stages")},
    }
    if source:
        out[SOURCE_KEY] = source
    return out


def read_events(path: Path):
    events = []
    for i, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = line.strip()
        if not line:
            continue
        try:
            events.append(json.loads(line))
        except json.JSONDecodeError as e:
            raise SystemExit(f"{path}:{i}: not JSON ({e})")
    return events


def serialize(obj):
    """One spelling, so --check compares content and never formatting."""
    return json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("jsonl", nargs="?", type=Path, help="a run.jsonl (default: the committed capture's source)")
    ap.add_argument("--write", action="store_true", help=f"update {CAPTURE.relative_to(ROOT)}")
    ap.add_argument("--check", action="store_true", help="fail if the committed capture drifted from its source")
    args = ap.parse_args()

    src = args.jsonl
    if src is None:
        if not CAPTURE.exists():
            return fail(f"no {CAPTURE.relative_to(ROOT)} yet — run the pipeline with "
                        "--capture and pass its run.jsonl here.")
        committed = json.loads(CAPTURE.read_text())
        rel = committed.get(SOURCE_KEY)
        if not rel:
            return fail(f"{CAPTURE.relative_to(ROOT)} has no {SOURCE_KEY} — it cannot be "
                        "re-derived, so it cannot be trusted. Regenerate it with --write.")
        src = ROOT / rel

    if not src.exists():
        return fail(f"missing source capture: {src}\n"
                    "     The committed page data points at a run.jsonl that is not in the tree.\n"
                    "     Re-run the pipeline with --capture, or commit the run.jsonl it produced.")

    events = read_events(src)

    if args.write:
        # Adopt the source into the tree first, then fold from where it will actually
        # live, so the committed pointer is the path the gate will re-read.
        run_id = next((e.get("runId") for e in events if e["kind"] == "run.begin"), None)
        if not run_id:
            return fail("the capture has no runId; it cannot be filed.")
        kept = CAPTURES / str(run_id) / "run.jsonl"
        if src.resolve() != kept.resolve():
            kept.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src, kept)
            print(f"kept  {kept.relative_to(ROOT)}")
        folded = fold(events, source=str(kept.relative_to(ROOT)))
        CAPTURE.parent.mkdir(parents=True, exist_ok=True)
        CAPTURE.write_text(serialize(folded))
        print(f"wrote {CAPTURE.relative_to(ROOT)}  "
              f"({folded['counts']['ok']} ok, {folded['counts']['skipped']} skipped, "
              f"{folded['counts']['failed']} failed)")
        return 0

    folded = fold(events, source=str(src.resolve().relative_to(ROOT)))

    if args.check:
        if not CAPTURE.exists():
            return fail(f"no {CAPTURE.relative_to(ROOT)}; /run has nothing to render.")
        if CAPTURE.read_text() != serialize(folded):
            return fail(
                f"{CAPTURE.relative_to(ROOT)} does not match a fresh fold of {src.relative_to(ROOT)}.\n"
                "     The page would show something the run did not produce.\n"
                f"     Fix: .venv/bin/python tools/capture/summarize.py {src.relative_to(ROOT)} --write")
        print(f"ok    /run matches {src.relative_to(ROOT)}  "
              f"({folded['counts']['ok']} ok, {folded['counts']['skipped']} skipped, "
              f"{folded['counts']['failed']} failed)")
        return 0

    print(serialize(folded))
    return 0


def fail(msg):
    print(f"\033[31mFAIL\033[0m  {msg}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
